<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="Tracks\**\*.mp3" />
    <EmbeddedResource Include="Videos\**\*" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ppy.osu.Framework" Version="2025.826.0" />
    <PackageReference Include="ppy.osu.Framework.NativeLibs" Version="2025.806.0-nativelibs" />
  </ItemGroup>
</Project>
