<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Transfer.TestProject.props" />
  <PropertyGroup Label="Project">
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\Transfer.Game\Transfer.Game.csproj" />
  </ItemGroup>
  <ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
    <PackageReference Include="ppy.osu.framework" Version="2025.826.0" />
    <PackageReference Include="ppy.osu.Framework.NativeLibs" Version="2025.806.0-nativelibs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Visual\" />
  </ItemGroup>
</Project>
