@startuml VideoInterface

!pragma teoz true

skinparam sequenceMessageAlign right
skinparam responseMessageBelowArrow true
skinparam Handwritten false
skinparam backgroundColor #434B4D
skinparam lifelineStrategy solid

skinparam sequence{
    ParticipantFontName FiraCode Nerd Font
    ParticipantFontSize 20
    ParticipantFontStyle bold
    ActorBorderColor DeepSkyBlue
}

header <b>Video Interface

autonumber "<b>[000]"
actor "<b>User" as user order 0 #blue
participant "<b>App" as app order 1 #WhiteSmoke 
participant "Track" as track order 6 #HotPink 
participant "Video Container" as video order 2 #green 
participant "Video Split" as vs order 5 #green 
participant "Temp Store" as ts order 4 #red



user -[#blue]>(0) app: <color #f0f>Path to video</color>
& app -[#blue]>(20) video: <color #f0f>Path to video</color>
video -[#blue]>(10) ts: <color #f0f>Path To Video</color>
ts -[#blue]>(10) vs: <color #f0f>Path To Video</color>
vs --[#green]>> ts: <b>Audio Path
ts -[#blue]> track: <color #f0f>Stream audio</color>
track --[#green]>> video: <b>Track
opt#434B4D #LightBlue Video path is null
    video --[#green]>>(5) app: <b>Return video
    ||10||
else #BlueViolet
    video --[#green]>>(5) app: <b>Choice path
    ||10||
end
track --[#green]>>(10) video: <b>Audio



& app --[#green]>>(5) user: <b>Video

@enduml
