name: .NET Core Desktop

on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: Transfer.sln # Replace with your solution name, i.e. MyWpfApp.sln.
      Release_Name: Trasfer.Desktop/Transfer.Desktop.csproj
      Test_Project_Path: Transfer.Game.Tests/Transfer.Game.Tests.csproj # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          # A specific version to download, may also be "release" or a specific version
          # like "6.1.0". At the moment semver specifiers (i.e. >=6.1.0) are supported
          # only on Windows, on other platforms they are allowed but version is matched
          # exactly regardless.
          ffmpeg-version: release
          # Target architecture of the ffmpeg executable to install. Defaults to the
          # system architecture. Only x64 and arm64 are supported (arm64 only on Linux).
          architecture: ""
          # Linking type of the binaries. Use "shared" to download shared binaries and
          # "static" for statically linked ones. Shared builds are currently only available
          # for windows releases. Defaults to "static"
          linking-type: static
          # As of version 3 of this action, builds are no longer downloaded from GitHub
          # except on Windows: https://github.com/GyanD/codexffmpeg/releases.
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Execute unit tests
        run: dotnet test
        continue-on-error: true

      - name: Build the application
        run: dotnet build $env:Release_Name -c $env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Publish Transfer.Desktop
        run: dotnet publish $env:Solution_Name -c $env:Configuration -r linux-x64 --self-contained -o ./publish
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Zip the publish folder
        run: tar -czf ./publish/Transfer.tar.gz -C ./publish .

      - name: Generate release log
        id: changelog
        run: |
          echo "## Change log" > changes
          git log -1 --pretty=format:"- %s" >> changes
          cat changes >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/Transfer.tar.gz
          asset_name: Transfer.tar.gz
          asset_content_type: application/gzip
