name: .NET Core Desktop

on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: Transfer.sln                         
      Test_Project_Path: Transfer.Game.Tests/Transfer.Game.Tests.csproj                     
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe (only for Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v2

    #- name: Execute unit tests
     # run: dotnet test

    - name: Restore the application
      run: |
        if [ "${{ matrix.os }}" == 'windows-latest' ]; then
          dotnet restore $Solution_Name --configuration $Configuration
        else
          dotnet restore $Solution_Name /p:Configuration=$Configuration /p:Platform="Any CPU"
        fi
      env:
        Solution_Name: Transfer.sln
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: |
        if [ "${{ matrix.os }}" == 'windows-latest' ]; then 
          msbuild $Solution_Name /p:Configuration=$Configuration
        else
          dotnet build $Solution_Name -c $Configuration
        fi
      env:
        Solution_Name: Transfer.sln
        Configuration: ${{ matrix.configuration }}

    - name: Publish Transfer.Desktop
      run: dotnet publish Transfer.Desktop/Transfer.Desktop.csproj -c $Configuration -r ${{matrix.os == 'windows-latest' && 'win-x64' || 'linux-x64'}} --self-contained -o ./publish/Transfer.Desktop
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Zip the publish folder
      run: |
        if [ "${{ matrix.os }}" == 'windows-latest' ]; then
          Compress-Archive -Path ./publish/* -DestinationPath ./publish/Transfer.zip
        else
          zip -r ./publish/Transfer.zip ./publish/*
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/Transfer.zip
        asset_name: Transfer-${{ matrix.os }}.zip
        asset_content_type: application/zip
