name: .NET Core Desktop

on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: Transfer.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: Transfer.Game.Tests/Transfer.Game.Tests.csproj                     # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    #- name: Execute unit tests
     # run: dotnet test

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish Transfer.Desktop
      run: dotnet publish Transfer.Desktop/Transfer.Desktop.csproj -c $env:Configuration -r win-x64 --self-contained -o ./publish/Transfer.Desktop
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Zip the publish folder
      run: Compress-Archive -Path ./publish/* -DestinationPath ./publish/Transfer.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/Transfer.zip
        asset_name: Transfer.zip
        asset_content_type: application/zip
